# Generated by Django 3.2.9 on 2021-12-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_taskitem_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='date_time_set',
        ),
    ]
