# Generated by Django 3.2.9 on 2021-12-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_remove_taskitem_date_time_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='date_time_modified',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='due_date_time',
        ),
    ]
